#!/bin/bash

echo "🐳 Configuración de permisos Docker para ZienShield"
echo "=============================================="
echo ""
echo "EJECUTA ESTOS COMANDOS MANUALMENTE (requieren sudo):"
echo ""
echo "1️⃣ Agregar usuario al grupo docker:"
echo "sudo usermod -aG docker gacel"
echo ""
echo "2️⃣ Aplicar cambios de grupo (elige una opción):"
echo "   OPCIÓN A - Recargar grupos sin cerrar sesión:"
echo "   newgrp docker"
echo ""
echo "   OPCIÓN B - Reiniciar sesión SSH (más seguro):"
echo "   exit  # y volver a conectar"
echo ""
echo "3️⃣ Verificar que funciona:"
echo "docker --version"
echo "docker ps"
echo ""
echo "4️⃣ Iniciar servicios de monitoreo:"
echo "cd /home/gacel/zienshield"
echo "docker-compose -f docker-compose.monitoring.yml up -d"
echo ""
echo "========================================="
echo "Estado actual:"
echo "Usuario: $(whoami)"
echo "Grupos actuales: $(groups)"
echo "Grupo docker requerido: ❌ (no está en el grupo docker)"
echo ""
echo "Después de ejecutar los comandos, deberías ver:"
echo "Grupos: gacel users docker"