#!/bin/bash

echo "📊 Importando Dashboard de ZienShield a Grafana"
echo "=============================================="
echo ""
echo "🔗 Accede a Grafana: http://194.164.172.92:3002"
echo "👤 Usuario: admin"
echo "🔑 Contraseña: zienshield2024"
echo ""
echo "📋 Para importar el dashboard manualmente:"
echo "1. Ve a '+' (Create) > Import"
echo "2. Carga el archivo: monitoring/grafana/dashboards/zienshield-main-dashboard.json"
echo "3. Selecciona el datasource 'Prometheus'"
echo "4. Haz clic en 'Import'"
echo ""
echo "📈 Dashboard incluye:"
echo "✅ Usuarios Activos"
echo "✅ Eventos de Seguridad por Segundo"
echo "✅ Total de Empresas/Tenants"
echo "✅ Agentes Conectados"
echo "✅ CPU del Servidor"
echo "✅ Memoria del Sistema"
echo "✅ Requests HTTP por Segundo"
echo "✅ Duración de Requests"
echo "✅ Uso de Disco"
echo "✅ Load Average"
echo ""
echo "🔄 Actualización automática cada 30 segundos"
echo ""
echo "💡 ALTERNATIVA - Importar via API:"
echo "curl -X POST \\"
echo "  http://194.164.172.92:3002/api/dashboards/db \\"
echo "  -H 'Authorization: Basic YWRtaW46emllbnNoaWVsZDIwMjQ=' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d @monitoring/grafana/dashboards/zienshield-main-dashboard.json"
echo ""

# Verificar que las métricas estén disponibles
echo "🔍 Verificando métricas disponibles:"
echo -n "Prometheus: "
curl -s http://194.164.172.92:9090/api/v1/label/__name__/values | grep -c zienshield || echo "0"
echo -n "ZienShield Metrics: "
curl -s http://194.164.172.92:3001/metrics | grep -c "zienshield_" || echo "0"