#!/bin/bash

echo "🛠️ Configuración manual de monitoreo ZienShield"
echo "Como Docker requiere permisos sudo, aquí están las alternativas:"
echo ""
echo "OPCIÓN 1: Configurar permisos Docker (recomendado):"
echo "sudo usermod -aG docker \$USER"
echo "newgrp docker"
echo "docker-compose -f docker-compose.monitoring.yml up -d"
echo ""
echo "OPCIÓN 2: Instalar Prometheus y Grafana nativamente:"
echo "# Descargar Prometheus"
echo "wget https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz"
echo "tar -xzf prometheus-2.45.0.linux-amd64.tar.gz"
echo "cd prometheus-2.45.0.linux-amd64"
echo "cp ../monitoring/prometheus/prometheus.yml ."
echo "./prometheus --config.file=prometheus.yml --web.listen-address=0.0.0.0:9090 &"
echo ""
echo "# Descargar Node Exporter"
echo "wget https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz"
echo "tar -xzf node_exporter-1.6.0.linux-amd64.tar.gz"
echo "cd node_exporter-1.6.0.linux-amd64"
echo "./node_exporter --web.listen-address=0.0.0.0:9100 &"
echo ""
echo "OPCIÓN 3: Usar servicios en la nube (Grafana Cloud, etc.)"
echo ""
echo "📊 Para verificar que tu backend ya tiene métricas:"
curl http://194.164.172.92:3001/api/system/server-metrics